### ISSUE TITLE
Ports 40000-49999/tcp

### ISSUE THREAD

**Issue by christian-2** [edumeet/edumeet-docker#12]
According to `Dockerfile` and `docker-compose.yml`, `mm` only publishes ports 40000-49999/udp:
```
EXPOSE 40000-49999/udp
```
```
ports:
- "40000-49999:40000-49999/udp"
```

However, since `mm` runs with [`network_mode: "host"`](https://docs.docker.com/network/host/) the set of actually published ports also comprises 40000-49999/tcp. These TCP ports are e.g. important for meeting participants who may traverse firewalls with `openssh`/SOCKS5 (and `forceTcp=true`). `README.md` (in `havfo/multiparty-meeting`) and `roles/mm/files/ferm.conf` (in `misi/mm-ansible`) already refer to them.

IMO they should also be listed in `Dockerfile` and `docker-compose.yml` to enhance documentation and consistency.

**Comment by misi** [comment]
I fully agree..

**Comment by misi** [comment]
network mode: host  conflicts with defining ports so it is commented out in the last commit, but for documentation it is there.
