### ISSUE TITLE
Server starts but webapp is not accesible

### ISSUE THREAD

**Issue by helfio** [edumeet/edumeet-docker#16]
Hi,

I'm trying to deploy this new release but I'm not able to access the webapp.

I ge the following output running 
`$ sudo docker-compose up`

having the .env file like this

> BASEDIR=/opt
> EDUMEET=edumeet
> NODE_ENV=production
> SERVER_DEBUG=
> SERVER_DEBUG=mediasoup*
> TAG=3.3.0
> BRANCH=master
> REACT_APP_DEBUG='*'

> Starting ouroboros    ... done
> Starting mm_redis_1 ... done
> Starting mm_edumeet_1 ... done
> Attaching to mm_redis_1, ouroboros, mm_edumeet_1
> edumeet_1    | Container starting up...
> redis_1      | 1:C 04 Jul 2020 11:27:55.749 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis_1      | 1:C 04 Jul 2020 11:27:55.749 # Redis version=6.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
> redis_1      | 1:C 04 Jul 2020 11:27:55.750 # Configuration loaded
> redis_1      |                 _._                                                  
> redis_1      |            _.-``__ ''-._                                             
> redis_1      |       _.-``    `.  `_.  ''-._           Redis 6.0.5 (00000000/0) 64 bit
> redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
> redis_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
> redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
> redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
> redis_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
> redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
> redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
> redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
> redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
> redis_1      |  |    `-._`-._        _.-'_.-'    |                                  
> redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
> redis_1      |       `-._    `-.__.-'    _.-'                                       
> redis_1      |           `-._        _.-'                                           
> redis_1      |               `-.__.-'                                               
> redis_1      | 
> redis_1      | 1:M 04 Jul 2020 11:27:55.792 # Server initialized
> redis_1      | 1:M 04 Jul 2020 11:27:55.792 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis_1      | 1:M 04 Jul 2020 11:27:55.798 * Loading RDB produced by version 6.0.5
> redis_1      | 1:M 04 Jul 2020 11:27:55.798 * RDB age 9 seconds
> redis_1      | 1:M 04 Jul 2020 11:27:55.798 * RDB memory usage when created 0.77 Mb
> redis_1      | 1:M 04 Jul 2020 11:27:55.799 * DB loaded from disk: 0.005 seconds
> redis_1      | 1:M 04 Jul 2020 11:27:55.799 * Ready to accept connections
> ouroboros    | 2020-07-04 13:27:59 : INFO : ouroboros : Version: 1.4.3-master
> ouroboros    | 2020-07-04 13:27:59 : INFO : config : Cron configuration is valid. Using Cron schedule ['*', '2', '*', '*', '*']
> edumeet_1    | - process.env.DEBUG: mediasoup*
> edumeet_1    | - config.mediasoup.worker.logLevel: warn
> edumeet_1    | - config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]
> edumeet_1    |   mediasoup createWorker() +0ms
> edumeet_1    |   mediasoup:Worker constructor() +0ms
> edumeet_1    |   mediasoup:Worker spawning worker process: /opt/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999 +2ms
> edumeet_1    |   mediasoup:Channel constructor() +0ms
> edumeet_1    |   mediasoup:PayloadChannel constructor() +0ms
> edumeet_1    |   mediasoup:Worker worker process running [pid:13] +283ms

These are my config files
[server_config.txt](https://github.com/edumeet/edumeet-docker/files/4872778/server_config.txt)
[app_config.txt](https://github.com/edumeet/edumeet-docker/files/4872779/app_config.txt)

I also tried the vanilla configs without success. Any idea what I am doing wrong?

**Comment by volkankoc** [comment]
I have the same problem
please help

**Comment by helfio** [comment]
Hi, I forgot about his issue. I just messed up my config files trying to reuse 
part of them from previous versions. 

@volkankoc I did try a complete vanilla config files and it worked. Once I did 
that, started modifying them to my needs.

**Comment by so010** [comment]
@volkankoc complete new config?
If not try to start from scratch with fresh config.

**Comment by JagdishTech** [comment]
Same Problem for me.
![image](https://user-images.githubusercontent.com/89624981/145940103-50b5c82d-b0c4-40e1-b3ee-744d208934eb.png)
