### ISSUE TITLE
An error occured while accessing your microphone

### ISSUE THREAD

**Issue by sorincocorada** [edumeet/edumeet-docker#18]
Hi, 
I have installed the docker version (edumeet/edumeet:latest), added server certificates and turn server. However when I'm trying to Join a room I'm always getting "An error occurred while accessing your microphone". I have tried with different browsers, desktop and mobile, but the result is always the same. 
The Chat, raise hand and file sharing  work.
The video is shown only locally and not available to the other party.

Could you please give me some hints on what I have to investigate?

**Comment by sorincocorada** [comment]
It works after replacing the config files with the ones from edumeet

**Comment by ransomhmc** [comment]
@sorincocorada hi, i am seeing same error, replacing my server conf with `https://github.com/edumeet/edumeet` leads to a different error message when starting eduMeet container:
```
ReplyError: Ready check failed: NOAUTH Authentication required.
```

could you please describe which branch/tag you're using? and modifications on server/config.js to fix microphone issue?

**Comment by sorincocorada** [comment]
I am using the dev branch (docker tag dev). I haven't performed any special configurations, just replaced the configuration files (client and server) and then added my turn server config, adjusted the path for the certificates.
