### ISSUE TITLE
AWS EC2 AMI - Remote Users' Audio & Video is not coming through

### ISSUE THREAD

**Issue by sabkaraja** [edumeet/edumeet-docker#19]
Hi

I created an Amazon EC2 AMI image. and installed docker on it. 

I have opened 22,80,443,40000-49999 ports on the AWS EC2 instance security group. The docker instance runs pretty well. and users are able to login. However remote users' video and audio is not visible at all. Chat messages are available. 

I guess thats because of the TCP/UDP ports are open as well

>     ports:
>       - "80:80"
>       - "443:443"
>       - "40000-49999:40000-49999"
>       - "40000-49999:40000-49999/udp"
>     network_mode: host

When I test from another machine - 

> nc -zw3 65.0.21.130 49999 && echo "open" || echo "close"
> close

returns closed always.

**Comment by krihal** [comment]
Did you ever find a solution? I'm in the same situation.
