### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by christian-2** [edumeet/edumeet-docker#20]
The Prometheus exporter (see havfo/multiparty-meeting#222, `prom.md`) could serve as the basis for a monitoring dashboard (see havfo/multiparty-meeting#381). Users in environments without existing Prometheus monitoring may benefit from a related new capability inside `docker-compose.yml` as follows:

* activate Prometheus exporter in `configs/server/config.js`
* deploy Node Exporter from [`prom/node-exporter`](https://hub.docker.com/r/prom/node-exporter/)
* deploy Prometheus from [`prom/prometheus`](https://hub.docker.com/r/prom/prometheus)
* configure jobs `mm-exporter` and `node-exporter` into Prometheus
* deploy Grafana from [`grafana/grafana`](https://hub.docker.com/r/grafana/grafana)
* configure dashboard Multiparty Meeting with panels Mediasoup (as pictured in havfo/multiparty-meeting#222) and Rooms (e.g. as [table panel](https://grafana.com/docs/grafana/latest/panels/visualizations/table-panel)) into Grafana
* configure e.g. dashboard [Node Exporter Full](https://grafana.com/grafana/dashboards/1860) into Grafana

**Comment by christian-2** [comment]
@misi I have moved on to other things by now. I had asked for feedback back in May and since there were only two related votes (see above), it did not seem worthwhile to pursue this further in terms of preparing a PR.

**Comment by misi** [comment]
@christian-2 I am so sorry I was busy with other duties unfortunately. Thanks for your fast answer!
