### ISSUE TITLE
settings for IN and OUT audio device are no longer split in edumeet 4.x

### ISSUE THREAD

**Issue by maxadamo** [edumeet/edumeet-docker#52]
I had a look onto https://edumeet-v4-demo.geant.org/ and it seems that input and output audio devices have been gathered together. 

Would it be possible to re-introduce the settings available on the version 3.x, which allows to pick the microphone and the speaker from different devices?

**Comment by maxadamo** [comment]
I have tried to use the default device from my laptop, but I the sound output doesn't seem to work

**Comment by havfo** [comment]
Fixed in latest PR to edumeet-client
